name: video-common validation

on:
  pull_request:
    paths:
      - 'libs/common/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install dependencies
        run: yarn install --ignore-scripts --frozen-lockfile

      - name: Build
        run: yarn nx run common:build

      - name: Hash check
        run: yarn nx run common:hash:check
